package com.ovidijus.miliauskas.TVprograms.mybatis.dao;

import com.ovidijus.miliauskas.TVprograms.mybatis.model.Comments;
import java.util.List;

public interface CommentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMMENTS
     *
     * @mbg.generated Tue Apr 27 21:03:02 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMMENTS
     *
     * @mbg.generated Tue Apr 27 21:03:02 EEST 2021
     */
    int insert(Comments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMMENTS
     *
     * @mbg.generated Tue Apr 27 21:03:02 EEST 2021
     */
    Comments selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMMENTS
     *
     * @mbg.generated Tue Apr 27 21:03:02 EEST 2021
     */
    List<Comments> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMMENTS
     *
     * @mbg.generated Tue Apr 27 21:03:02 EEST 2021
     */
    int updateByPrimaryKey(Comments record);
}