package com.ovidijus.miliauskas.TVprograms.mybatis.dao;

import com.ovidijus.miliauskas.TVprograms.mybatis.model.Person;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface PersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PERSON
     *
     * @mbg.generated Tue Apr 27 21:03:02 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PERSON
     *
     * @mbg.generated Tue Apr 27 21:03:02 EEST 2021
     */
    int insert(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PERSON
     *
     * @mbg.generated Tue Apr 27 21:03:02 EEST 2021
     */
    Person selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PERSON
     *
     * @mbg.generated Tue Apr 27 21:03:02 EEST 2021
     */
    List<Person> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PERSON
     *
     * @mbg.generated Tue Apr 27 21:03:02 EEST 2021
     */
    int updateByPrimaryKey(Person record);
}