package com.ovidijus.miliauskas.TVprograms.mybatis.dao;

import com.ovidijus.miliauskas.TVprograms.mybatis.model.Tvprogram;
import java.util.List;

public interface TvprogramMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TVPROGRAM
     *
     * @mbg.generated Tue Apr 27 21:03:02 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TVPROGRAM
     *
     * @mbg.generated Tue Apr 27 21:03:02 EEST 2021
     */
    int insert(Tvprogram record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TVPROGRAM
     *
     * @mbg.generated Tue Apr 27 21:03:02 EEST 2021
     */
    Tvprogram selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TVPROGRAM
     *
     * @mbg.generated Tue Apr 27 21:03:02 EEST 2021
     */
    List<Tvprogram> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TVPROGRAM
     *
     * @mbg.generated Tue Apr 27 21:03:02 EEST 2021
     */
    int updateByPrimaryKey(Tvprogram record);
}