package com.ovidijus.miliauskas.TVprograms.mybatis.model;

public class Tvprogram {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TVPROGRAM.ID
     *
     * @mbg.generated Tue Apr 27 21:03:02 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TVPROGRAM.TITLE
     *
     * @mbg.generated Tue Apr 27 21:03:02 EEST 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TVPROGRAM.VIEWS
     *
     * @mbg.generated Tue Apr 27 21:03:02 EEST 2021
     */
    private Integer views;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TVPROGRAM.PERSONID
     *
     * @mbg.generated Tue Apr 27 21:03:02 EEST 2021
     */
    private Integer personid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TVPROGRAM.ID
     *
     * @return the value of PUBLIC.TVPROGRAM.ID
     *
     * @mbg.generated Tue Apr 27 21:03:02 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TVPROGRAM.ID
     *
     * @param id the value for PUBLIC.TVPROGRAM.ID
     *
     * @mbg.generated Tue Apr 27 21:03:02 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TVPROGRAM.TITLE
     *
     * @return the value of PUBLIC.TVPROGRAM.TITLE
     *
     * @mbg.generated Tue Apr 27 21:03:02 EEST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TVPROGRAM.TITLE
     *
     * @param title the value for PUBLIC.TVPROGRAM.TITLE
     *
     * @mbg.generated Tue Apr 27 21:03:02 EEST 2021
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TVPROGRAM.VIEWS
     *
     * @return the value of PUBLIC.TVPROGRAM.VIEWS
     *
     * @mbg.generated Tue Apr 27 21:03:02 EEST 2021
     */
    public Integer getViews() {
        return views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TVPROGRAM.VIEWS
     *
     * @param views the value for PUBLIC.TVPROGRAM.VIEWS
     *
     * @mbg.generated Tue Apr 27 21:03:02 EEST 2021
     */
    public void setViews(Integer views) {
        this.views = views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TVPROGRAM.PERSONID
     *
     * @return the value of PUBLIC.TVPROGRAM.PERSONID
     *
     * @mbg.generated Tue Apr 27 21:03:02 EEST 2021
     */
    public Integer getPersonid() {
        return personid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TVPROGRAM.PERSONID
     *
     * @param personid the value for PUBLIC.TVPROGRAM.PERSONID
     *
     * @mbg.generated Tue Apr 27 21:03:02 EEST 2021
     */
    public void setPersonid(Integer personid) {
        this.personid = personid;
    }
}